from __future__ import annotations

import pandas as pd

FEATURE_DICTIONARY: list[dict[str, str]] = [
    {
        "mart_name": "mart_customer_features",
        "feature_name": "recency_days",
        "dtype": "int",
        "business_definition": "Days between customer last completed order and anchor date.",
        "usage_notes": "Primary churn recency signal; higher often means higher churn risk.",
    },
    {
        "mart_name": "mart_customer_features",
        "feature_name": "online_order_share",
        "dtype": "float",
        "business_definition": "Share of completed orders placed online.",
        "usage_notes": "Use with store_order_share and preferred_channel for channel strategy.",
    },
    {
        "mart_name": "mart_campaign_response",
        "feature_name": "response_flag_30d",
        "dtype": "int",
        "business_definition": "Binary indicator of 30-day conversion after assignment.",
        "usage_notes": "Base target for campaign response and uplift baselines.",
    },
    {
        "mart_name": "mart_campaign_response",
        "feature_name": "pre_90d_revenue",
        "dtype": "float",
        "business_definition": "Revenue generated by customer in 90 days before campaign assignment.",
        "usage_notes": "Use as pre-treatment baseline in uplift analyses.",
    },
    {
        "mart_name": "mart_product_demand",
        "feature_name": "units_sold",
        "dtype": "int",
        "business_definition": "Total weekly units sold for product-location grain.",
        "usage_notes": "Primary target for forecasting module.",
    },
    {
        "mart_name": "mart_product_demand",
        "feature_name": "rolling_4w_avg_units",
        "dtype": "float",
        "business_definition": "Four-week rolling average demand for product-location.",
        "usage_notes": "Useful lagged smoothed feature for baseline forecasting models.",
    },
    {
        "mart_name": "mart_returns_risk",
        "feature_name": "return_flag",
        "dtype": "int",
        "business_definition": "Binary indicator that order item has an associated return.",
        "usage_notes": "Base supervised target for return risk modeling.",
    },
    {
        "mart_name": "mart_returns_risk",
        "feature_name": "prior_customer_return_rate",
        "dtype": "float",
        "business_definition": "Historical return rate for customer before current item.",
        "usage_notes": "High-signal risk feature; monitor leakage windows carefully.",
    },
    {
        "mart_name": "mart_recommendation_interactions",
        "feature_name": "interaction_score",
        "dtype": "float",
        "business_definition": "Weighted implicit feedback score from purchases, events, and reviews.",
        "usage_notes": "Use for ranking candidates in recommendation baselines.",
    },
    {
        "mart_name": "mart_recommendation_interactions",
        "feature_name": "product_rank_for_customer",
        "dtype": "int",
        "business_definition": "Rank of product by interaction score within customer history.",
        "usage_notes": "Useful for top-k recommendation evaluation and filters.",
    },
    {
        "mart_name": "mart_store_week_performance",
        "feature_name": "net_revenue",
        "dtype": "float",
        "business_definition": "Weekly revenue at store-location grain.",
        "usage_notes": "Core metric for store performance and weekly planning.",
    },
    {
        "mart_name": "mart_store_week_performance",
        "feature_name": "rolling_4w_avg_revenue",
        "dtype": "float",
        "business_definition": "Four-week rolling average of store revenue.",
        "usage_notes": "Supports trend analysis and anomaly detection baselines.",
    },
]


def feature_dictionary_df() -> pd.DataFrame:
    return pd.DataFrame(FEATURE_DICTIONARY)
